version: '3.8'

services:
  api:
    build: .
    container_name: subtitle_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build: ./frontend
    container_name: subtitle_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api